### ISSUE TITLE
生成式任务里所谓问答模型（Text-Generation, T5 Based）似乎更像是阅读理解任务

### ISSUE THREAD

**Issue by yaleimeng** [HarderThenHarder/transformers_tasks#10]
因为推理的时候还需要给一个问题和一段上下文。。跟抽取式任务也差不多，只不过答案是用模型自己的话复述。
而不像一般的问答任务那样只提供问题即可。

**Comment by HarderThenHarder** [comment]
Hi，抱歉因为起名的原因让您有所误解。您说的没错，代码里的 answer_generation 任务更像是一个生成式的阅读理解任务。如果您希望训练一个单轮问答模型，您可以尝试使用 [这里](https://github.com/HarderThenHarder/transformers_tasks/blob/main/data_augment/filling_model/readme.md) 的代码，将训练集替换为「问题」和「答案」的 pair。
