### ISSUE TITLE
RuntimeError: The size of tensor a (16) must match the size of tensor b (17)

### ISSUE THREAD

**Issue by archwolf118** [HarderThenHarder/transformers_tasks#11]
Thanks for this good project.
but when I run "RLHF project": 
```
python ppo_sentiment_example.py
```
I got :"RuntimeError: The size of tensor a (16) must match the size of tensor b (17) at non-singleton dimension 1"
I am a newer of transformer, Could you please tell me what is the problem. Thank you!

**Comment by HarderThenHarder** [comment]
Hi, sorry for the inconvenience. could you give me more information about your error

**Comment by archwolf118** [comment]
> Hi, sorry for the inconvenience. Could you give me more information about your error code(e.g. error line), provide me a screenshot if possible.
![image](https://user-images.githubusercontent.com/7391017/218740428-ba7400d2-6742-4da3-a03f-49834180cd32.png)

···
cd RLHF
python ppo_sentiment_example.py
···
I got above wrong info. Thank you. 
It say "RLHF/trl/ppo.py"  line 242  ```returns = advantages + values```, adavantages and values have differrent size.

Thanks!

**Comment by HarderThenHarder** [comment]
I fixed some bugs, try to pull the latest version please. Let me know if you still get this problem.

**Comment by archwolf118** [comment]
> I fixed some bugs, please try to pull the latest version. Let me know if you still get this problem.

Thanks, It works! :)
