### ISSUE TITLE
运行RLHF/train_reward_model.sh的疑问

### ISSUE THREAD

**Issue by yaleimeng** [HarderThenHarder/transformers_tasks#12]
1，训练过程中，loss是从-0.6左右逐渐下降到-0.9以下，但为什么acc虽然会上下跳动，却始终是0.1的整数倍呢？
2，粗看了一下train_reward_model.py代码， train()函数中末尾，在评估的时候， acc = evaluate_model(model, eval_dataloader)，调用了这个函数。但是在evaluate_model(model, data_loader)函数中，又有一行 model.train()，这是什么用意呢？

**Comment by HarderThenHarder** [comment]
Hi，因为在评估函数的开头 [这里](https://github.com/HarderThenHarder/transformers_tasks/blob/a726e02c4a10967200afd6b860f3720be40238d4/RLHF/train_reward_model.py#L68)，对模型进行了 model.eval()，所以在结束评估后需要恢复模型的训练模式，所以添加了 model.train()。

**Comment by HarderThenHarder** [comment]
关于您提出的第 1 个问题，可能是由于 [这个 issue](https://github.com/HarderThenHarder/transformers_tasks/issues/13#issuecomment-1430955454) 中提到的原因。我已经修复了评估函数，您可以尝试 pull 最新的代码来解决这个问题。

**Comment by yaleimeng** [comment]
确实是这个原因，修正之后acc就正常了。不过您在readme中的示例终端打印信息和结束截图都有点问题。
