### ISSUE TITLE
“在最后一位加上人工给的reward” 的出处

### ISSUE THREAD

**Issue by PYNing** [HarderThenHarder/transformers_tasks#16]
感谢作者的分享。仔细阅读源码后我有个疑问，请问下面这行代码有出处吗？如有，烦请给下名字或URL。谢谢！

https://github.com/HarderThenHarder/transformers_tasks/blob/main/RLHF/trl/ppo.py#L225

**Comment by HarderThenHarder** [comment]
出处在 [trl源码库](https://github.com/lvwerra/trl/blob/2e667be9d9f77466162257c4663872e82b12dea4/trl/trainer/ppo_trainer.py#L667-L668)，请问您对最后加上 human reward 这个做法有什么疑问吗？

**Comment by xiningnlp** [comment]
> 感谢作者的分享。仔细阅读源码后我有个疑问，请问下面这行代码有出处吗？如有，烦请给下名字或URL。谢谢！
> 
> https://github.com/HarderThenHarder/transformers_tasks/blob/main/RLHF/trl/ppo.py#L225

@PYNing  由于`reward`是定义在句子级别的，因此，一句话生成结束后，只能得到一个reward model赋予的`reward`。另一方面，传统的PG的`advantage`方法要求：每个时刻的`advantage`的值都需要和局末的游戏奖励（即本项目中的句字生成结束后的`reward`）挂钩，且局末奖励对每个时刻的advantage的值的贡献随着的距离局末时刻的距离呈指数衰减。

在loss方法中，每个序列在计算每个时刻的`advantage`值（对应代码中的`lastgaelam` 变量），是从后往前计算的，因此，为了配合这一计算逻辑，每个reward需要放在珍格最后。至于为何要从后往前算，具体请参考John Schulman 2017年的论文 https://arxiv.org/abs/1707.06347 ，Ch. 5. 解释了 advantage的计算公式，和代码是一一对应的。

**Comment by PYNing** [comment]
非常感谢您的提示！我再好好对一下论文！

**Comment by 2020zyc** [comment]
> > 感谢作者的分享。仔细阅读源码后我有个疑问，请问下面这行代码有出处吗？如有，烦请给下名字或URL。谢谢！
> > https://github.com/HarderThenHarder/transformers_tasks/blob/main/RLHF/trl/ppo.py#L225
> 
> @PYNing 由于`reward`是定义在句子级别的，因此，一句话生成结束后，只能得到一个reward model赋予的`reward`。另一方面，传统的PG的`advantage`方法要求：每个时刻的`advantage`的值都需要和局末的游戏奖励（即本项目中的句字生成结束后的`reward`）挂钩，且局末奖励对每个时刻的advantage的值的贡献随着的距离局末时刻的距离呈指数衰减。
> 
> 在loss方法中，每个序列在计算每个时刻的`advantage`值（对应代码中的`lastgaelam` 变量），是从后往前计算的，因此，为了“配合”这一计算逻辑，每个reward需要放在reward数组的最后。至于为何要从后往前算，具体请参考John Schulman 2017年的论文 https://arxiv.org/abs/1707.06347 ，Ch. 5. 解释了 advantage的计算公式，和代码是一一对应的。

请教一下 reward的计算方式，为什么是用 log(Prob)-log(Prob_ref) 作为每个token action的reward呢？

**Comment by 2020zyc** [comment]
回答一下上面的问题：看到hf的文章，说是只用整句reward效果较差；kl作为token reward可以约束模型不要太偏离ref model，效果较好；
