### ISSUE TITLE
推理部分

### ISSUE THREAD

**Issue by yhc582825016** [HarderThenHarder/transformers_tasks#17]
请问可以提供一份RLHF中GPT模型的推理代码吗？我看里面好像没有包含模型保存和重新加载的部分

**Comment by yaleimeng** [comment]
好像确实是啊。在terminal_main.py 与 ppo_sentiment_example.py 里面有调用ppo_trainer.step( )更新，但这个更新不知道有没有持久化，对保存的模型权重进行更新。

**Comment by HarderThenHarder** [comment]
Hi，我已经添加了该功能，您可以 pull 最新的代码来实现训练模型重加载和推理。

首先，您需要在训练阶段中保存训练模型，在 [这里](https://github.com/HarderThenHarder/transformers_tasks/blob/1facaa36b860ea0ef95c88d9471f99c9b5bbfdfa/RLHF/ppo_sentiment_example.py#L167) 定义模型存放路径。

完成训练后，您需要在 [这里](https://github.com/HarderThenHarder/transformers_tasks/blob/1facaa36b860ea0ef95c88d9471f99c9b5bbfdfa/RLHF/inference_ppo_gpt.py#L28) 修改训练模型的存放地址，加载模型后即可通过 `inference()` 函数进行模型推理。

```sh
python inference_ppo_gpt.py
```

![image](https://user-images.githubusercontent.com/36854507/220367509-d97dddab-0d88-4ecb-8df0-c0890b86c802.png)
