### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by Magic-Gj** [HarderThenHarder/transformers_tasks#2]
您好，我在运行你们的代码时，碰到了下图问题，现在报错说说是pytorch中的问题，我想咨询一下这种问题该如何解决。
![image](https://user-images.githubusercontent.com/107447700/212524650-40cc6a55-1db8-4695-a7dc-fc3064b45e7b.png)

**Comment by HarderThenHarder** [comment]
您尝试下重新下载预训练模型呢：
1. 先删除UIE路径下的「uie-base-zh」目录。
2. 重新运行 train.sh，程序会自动下载pretrained model。

如果重下之后还是存在该问题，请提供一下您的torch版本和transformers的版本。

**Comment by Magic-Gj** [comment]
重新下载模型后，依然存在该问题。
![image](https://user-images.githubusercontent.com/107447700/212531537-63030cdb-2fad-46dc-928e-29f95787a9b2.png)
按照您的要求给出库的版本如下：
torch              1.12.0
torchvision        0.13.1a0
transformers       4.22.1
![image](https://user-images.githubusercontent.com/107447700/212531600-b39b8827-bc28-4037-b82a-62c9b3421b64.png)

**Comment by HarderThenHarder** [comment]
我构建了和你提供的同样版本的 `torch` 和 `transformers`，程序能够正常运行。
我猜测可能是pretrained model没有下载完全，你看看 `uie-base-zh` 目录下，各个文件的大小是否和下图是一致的呢（尤其是 `pytorch_model.bin` 的大小）：
![image](https://user-images.githubusercontent.com/36854507/212532696-db03e502-13f5-483d-8081-d4f83ce2eb60.png)

**Comment by Magic-Gj** [comment]
文件都是有的，但是大小不一样，这应该怎么办？
![image](https://user-images.githubusercontent.com/107447700/212533152-d3f4b4b3-2a93-4faf-8dbe-5b06d58dd420.png)

**Comment by Magic-Gj** [comment]
需要修改train.py中的代码吗？
![image](https://user-images.githubusercontent.com/107447700/212533229-a7e11d92-7c83-44c3-9aae-09c6d845f451.png)

**Comment by HarderThenHarder** [comment]
应该是模型下载错误，尝试下手动下载：将[这里](https://huggingface.co/Pky/uie-base-zh/tree/main)的文件，放到 `uie-base-zh` 文件夹下。

**Comment by Magic-Gj** [comment]
按照您的回复，我把模型替换好了，然后直接运行train.sh文件吗？但是这样会不会程序重新自动下载模型，造成错误呢？希望您给出建议。

**Comment by HarderThenHarder** [comment]
是的，直接运行 `train.sh` 就好。程序会自动检测当前目录下有没有 `uie-base-zh` 文件夹，如果您已经将云端的文件夹下载了本地，就不会执行自动下载，所以您不用担心下好的模型会被覆盖的问题。
Note：云端的 `每一个文件` 都需要被下载到本地，不止是 `pytorch_model.bin`。

**Comment by Magic-Gj** [comment]
谢谢你，我的问题已经解决。@HarderThenHarder，您解决问题的态度十分棒，而且给出的建议十分实用！赞！！！
![image](https://user-images.githubusercontent.com/107447700/212859579-27e6fdbd-46ee-402b-85a2-6f56bbd88db2.png)
