### ISSUE TITLE
多卡训练求助？

### ISSUE THREAD

**Issue by Traceve** [HarderThenHarder/transformers_tasks#27]
RuntimeError: :0: cudaFuncSetAttribute(kernel_entry, cudaFuncAttributeMaxDynamicSharedMemorySize, integer_cast<int32_t>(launch_configs[0].smemSizeInBytes)): out of memory
/data1/software/anaconda3/envs/llm_env/lib/python3.8/site-packages/torch/autograd/__init__.py:200: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [8192, 2, 1], strides() = [2, 1, 2]
bucket_view.sizes() = [8192, 2, 1], strides() = [2, 1, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:323.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[16:26:30] WARNING  Sending process 17571 closing signal SIGTERM                                                                                                                                                                                          api.py:698
[16:26:31] ERROR    failed (exitcode: 1) local_rank: 1 (pid: 17572) of binary: /data1/software/anaconda3/envs/llm_env/bin/python 

单卡没问题，多卡会报显存溢出？

**Comment by Traceve** [comment]
> 

设置成10也不行，然后将layer降成10层还是会溢出呢。
![image](https://user-images.githubusercontent.com/37016580/228778685-59f29d0f-2bef-46ba-8f87-c64fef6a1748.png)

**Comment by HarderThenHarder** [comment]
您尝试在运行程序之后，观察一下显存利用情况呢？

看看是某一张卡爆了，还是所有卡都爆掉了。

在我测试中，项目中给的数据集在 --max_source_seq_len=400，--max_target_seq_len=300 的情况下双卡显存大概会在 `30G` 左右。

PS：使用 `watch -n 1 nvidia-smi` 实时查看显存状态 :)
