### ISSUE TITLE
关于模型训练的问题

### ISSUE THREAD

**Issue by chenchongyuan** [HarderThenHarder/transformers_tasks#36]
多卡训练，对验证集第一次验证后报错如下，想请问您这边遇到过这种情况吗

![image](https://user-images.githubusercontent.com/28033730/230563618-77586ac7-ec6c-41d8-9888-d7cb9bc836c1.png)
![image](https://user-images.githubusercontent.com/28033730/230563698-3c769787-c645-4ffd-8bc4-dfa7ddbed694.png)
![image](https://user-images.githubusercontent.com/28033730/230563761-1d9505ee-1dce-4f28-99e5-2e6fe0f0cd83.png)

**Comment by littlerookie** [comment]
@chenchongyuan 请问这个问题您这解决了吗，我也遇到了这个问题
