### ISSUE TITLE
最新更新代码后，模型训练保存出错

### ISSUE THREAD

**Issue by nieallen** [HarderThenHarder/transformers_tasks#39]
AttributeError: 'PeftModelForCausalLM' object has no attribute 'merge_and_unload'
AttributeError: 'LoraModel' object has no attribute 'merge_and_unload'
![image](https://user-images.githubusercontent.com/33852772/230884314-67dee11b-11fd-468d-a807-88a38c9b27e4.png)

**Comment by HarderThenHarder** [comment]
Hi，您需要重新更新一下 `peft` 的包：

```sh
pip uninstall peft
cd peft-chatglm
python setup.py install
```

**Comment by nieallen** [comment]
> Hi，您需要重新更新一下 `peft` 的包：
> 
> ```shell
> pip uninstall peft
> cd peft-chatglm
> python setup.py install
> ```

谢谢，已解决，请问为什么lora训练，模型文件保存这么大？这会使得磁盘空间占用很大

**Comment by HarderThenHarder** [comment]
考虑到推理速度和模型稳定性，我在存储模型的时候将 LoRA 参数和原始模型进行了合并，这样可以得到一个完整的原始模型。

**Comment by nieallen** [comment]
> 考虑到推理速度和模型稳定性，我在存储模型的时候将 LoRA 参数和原始模型进行了合并，这样可以得到一个完整的原始模型。

get
