### ISSUE TITLE
transformers==4.22.1

### ISSUE THREAD

**Issue by Victor-xx** [HarderThenHarder/transformers_tasks#5]
您好，没有transformers==4.22.1版本的呀

**Comment by HarderThenHarder** [comment]
可能是源用的不一样，可以找一个相近的transformers版本（或者最新版），应该不会有什么问题。

**Comment by archwolf118** [comment]
python3.6就没有4.22.1版本，最好用python3.7来训练。

**Comment by yaleimeng** [comment]
我用的最新版4.26，没什么问题
