### ISSUE TITLE
您好，我将bert-base-chinese换成了roberta-base，然后报错了

### ISSUE THREAD

**Issue by yumogu** [HarderThenHarder/transformers_tasks#7]
![image](https://user-images.githubusercontent.com/19318605/218247140-72822fd5-4624-4659-8be4-871ce2b27d8b.png)
您好！我把模型换成了roberta-base，然后报了上面的错误，我应该怎么修改代码！

**Comment by HarderThenHarder** [comment]
Hi，我已经将该问题修复。

**您可以通过 pull 最新的代码来解决这个问题**。

出现这个问题的原因：因为您使用了一个**不需要 token_type_ids 的模型（roberta-base）**。

在 Roberta 的 pretraining 过程中舍弃了 BERT 的 NSP（Next Sentence Prediction） 任务，这导致 roberta tokenizer 不会再返还 token_type_id 这一属性。

因此，我在 [这里](https://github.com/HarderThenHarder/transformers_tasks/blob/41c662879413217ca53b084ccda681d5b0967c0a/prompt_tasks/p-tuning/p_tuning.py#L199) 兼容了这种不需要 token_type_id 的模型输入，并在 [这里](https://github.com/HarderThenHarder/transformers_tasks/blob/41c662879413217ca53b084ccda681d5b0967c0a/prompt_tasks/p-tuning/utils.py#L106) 兼容了不同模型的数据转换格式。
