### ISSUE TITLE
mbti_questions.json 这个测试文件可以分享一下吗

### ISSUE THREAD

**Issue by zhongxing-mt** [HarderThenHarder/transformers_tasks#83]
在mbti测试中需要用到这个文件，不知道是否可以分享一下

**Comment by HarderThenHarder** [comment]
Hi，上传的时候忘了上载这个文件，抱歉，我将文件补在了[这里](https://github.com/HarderThenHarder/transformers_tasks/blob/main/LLM/llms_mbti/mbti_questions.json)。
