### ISSUE TITLE
ppo中 获取生成tokens的value 代码疑似有误

### ISSUE THREAD

**Issue by wangxicoding** [HarderThenHarder/transformers_tasks#9]
https://github.com/HarderThenHarder/transformers_tasks/blob/main/RLHF/trl/ppo.py#L203
`all_values.append(v[j, start-1:end-1])` 这里给value的起始下标-1了。
应该不需要-1，value直接预测的就是当前的状态值了。

**Comment by HarderThenHarder** [comment]
Hi，感谢您的指正~

**Comment by wangxicoding** [comment]
hello，看了你最新的commit，start = len(q) - 1 已经在query最后一个token的位置了，也不用-1了，估计最新issue 16不match 17就是这个问题。
![image](https://user-images.githubusercontent.com/10208305/218736179-38028333-5199-4e3d-868d-f5bbe97682b3.png)

**Comment by HarderThenHarder** [comment]
再次感谢， /比心，欢迎您持续关注 ^_^
